import type { VaultTopic } from "@/types";

export const vaultTopics: VaultTopic[] = [
  {
    slug: "cardiology",
    title: "Cardiology",
    shortTitle: "Cardio",
    questionCount: 42,
    tags: ["ACS", "ECG", "Arrhythmia", "Heart Failure"],
    acem_sections: ["2.1", "2.2", "2.3"],
    description: "ACS risk stratification, ECG interpretation, arrhythmia management, and acute heart failure in the Australasian context.",
  },
  {
    slug: "toxicology",
    title: "Toxicology",
    shortTitle: "Tox",
    questionCount: 38,
    tags: ["Overdose", "Antidotes", "NZ Poisons", "MDAC"],
    acem_sections: ["3.1", "3.2"],
    description: "NZ Poisons Centre protocols, antidote availability in district hospitals, and pharmacokinetic principles for the ACEM exam.",
  },
  {
    slug: "trauma-cap",
    title: "Trauma — Primary Survey",
    shortTitle: "Trauma CAP",
    questionCount: 35,
    tags: ["ATLS", "Haemorrhage Control", "Airway"],
    acem_sections: ["4.1", "4.2"],
    description: "ATLS 11th edition updates, damage control resuscitation, massive transfusion protocols (MTP) used in NZ trauma centres.",
  },
  {
    slug: "neuro",
    title: "Neurology & Neurosurgery",
    shortTitle: "Neuro",
    questionCount: 40,
    tags: ["Stroke", "SAH", "Seizure", "Headache"],
    acem_sections: ["5.1", "5.2", "5.3"],
    description: "Stroke thrombolysis criteria, SAH investigation pathways, status epilepticus management per Australasian guidelines.",
  },
  {
    slug: "paediatrics",
    title: "Paediatrics",
    shortTitle: "Paeds",
    questionCount: 45,
    tags: ["Fever", "Croup", "Bronchiolitis", "Safeguarding"],
    acem_sections: ["6.1", "6.2", "6.3"],
    description: "Paediatric resuscitation (Broselow/weight-based dosing), fever risk stratification, and mandatory reporting obligations in NZ/AU.",
  },
  {
    slug: "renal-resp",
    title: "Renal & Respiratory",
    shortTitle: "Renal/Resp",
    questionCount: 36,
    tags: ["AKI", "Asthma", "COPD", "ABG"],
    acem_sections: ["7.1", "7.2"],
    description: "ABG interpretation, NIV initiation criteria, acute kidney injury staging, and dialysis indications in the ED.",
  },
  {
    slug: "orthopaedics",
    title: "Orthopaedics",
    shortTitle: "Ortho",
    questionCount: 33,
    tags: ["Fractures", "Dislocations", "Imaging", "Compartment"],
    acem_sections: ["8.1", "8.2"],
    description: "Fracture classification, procedural sedation for reductions, compartment syndrome recognition, and growth plate injury in children.",
  },
  {
    slug: "radiology",
    title: "Radiology",
    shortTitle: "Radiology",
    questionCount: 30,
    tags: ["CXR", "CT", "Ultrasound", "POCUS"],
    acem_sections: ["9.1"],
    description: "Plain film, CT, and POCUS interpretation including FAST exam, lung ultrasound, and DVT assessment.",
  },
  {
    slug: "anaesthesia",
    title: "Anaesthesia & Airway",
    shortTitle: "Airway",
    questionCount: 28,
    tags: ["RSI", "Difficult Airway", "Ketamine", "NMBA"],
    acem_sections: ["10.1", "10.2"],
    description: "RSI drug selection, difficult airway algorithms, awake fibre-optic indications, and post-intubation management.",
  },
  {
    slug: "environmental",
    title: "Environmental Emergencies",
    shortTitle: "Environmental",
    questionCount: 25,
    tags: ["Hypothermia", "Envenomation", "Drowning", "Heat"],
    acem_sections: ["11.1"],
    description: "NZ/AU-specific envenomation (katipo, white-tail, Australian snakes), hypothermia rewarming, and drowning resuscitation.",
  },
  {
    slug: "og",
    title: "Obstetrics & Gynaecology",
    shortTitle: "O&G",
    questionCount: 30,
    tags: ["Ectopic", "PET", "PPH", "PV Bleeding"],
    acem_sections: ["12.1", "12.2"],
    description: "Ectopic pregnancy management, pre-eclampsia treatment thresholds, postpartum haemorrhage MTP activation.",
  },
  {
    slug: "clinical-chem",
    title: "Clinical Chemistry",
    shortTitle: "Clin Chem",
    questionCount: 28,
    tags: ["Electrolytes", "DKA", "HHS", "Acid-Base"],
    acem_sections: ["13.1"],
    description: "DKA vs HHS protocols, hyponatraemia correction rates, hyperkalaemia management, and acid-base problem-solving.",
  },
];

export function getTopicBySlug(slug: string): VaultTopic | undefined {
  return vaultTopics.find((t) => t.slug === slug);
}
