import type { VaultTopic } from "@/types";

export const vaultTopics: VaultTopic[] = [
  {
    slug: "cardiology",
    title: "Cardiology",
    shortTitle: "Cardio",
    questionCount: 42,
    tags: ["ACS", "ECG", "Arrhythmia", "Heart Failure"],
    acem_sections: ["2.1", "2.2", "2.3"],
    description: "ACS risk stratification, ECG interpretation, arrhythmia management, and acute heart failure in the Australasian context.",
  },
  {
    slug: "toxicology",
    title: "Toxicology",
    shortTitle: "Tox",
    questionCount: 38,
    tags: ["Overdose", "Antidotes", "NZ Poisons", "MDAC"],
    acem_sections: ["3.1", "3.2"],
    description: "NZ Poisons Centre protocols, antidote availability in district hospitals, and pharmacokinetic principles for the ACEM exam.",
  },
  {
    slug: "trauma-cap",
    title: "Trauma — Primary Survey",
    shortTitle: "Trauma CAP",
    questionCount: 35,
    tags: ["ATLS", "Haemorrhage Control", "Airway"],
    acem_sections: ["4.1", "4.2"],
    description: "ATLS 11th edition updates, damage control resuscitation, massive transfusion protocols (MTP) used in NZ trauma centres.",
  },
  {
    slug: "neuro",
    title: "Neurology & Neurosurgery",
    shortTitle: "Neuro",
    questionCount: 40,
    tags: ["Stroke", "SAH", "Seizure", "Headache"],
    acem_sections: ["5.1", "5.2", "5.3"],
    description: "Stroke thrombolysis criteria, SAH investigation pathways, status epilepticus management per Australasian guidelines.",
  },
  {
    slug: "paediatrics",
    title: "Paediatrics",
    shortTitle: "Paeds",
    questionCount: 45,
    tags: ["Fever", "Croup", "Bronchiolitis", "Safeguarding"],
    acem_sections: ["6.1", "6.2", "6.3"],
    description: "Paediatric resuscitation (Broselow/weight-based dosing), fever risk stratification, and mandatory reporting obligations in NZ/AU.",
  },
  {
    slug: "renal-resp",
    title: "Renal & Respiratory",
    shortTitle: "Renal/Resp",
    questionCount: 36,
    tags: ["AKI", "Asthma", "COPD", "ABG"],
    acem_sections: ["7.1", "7.2"],
    description: "ABG interpretation, NIV initiation criteria, acute kidney injury staging, and dialysis indications in the ED.",
  },
  {
    slug: "orthopaedics",
    title: "Orthopaedics",
    shortTitle: "Ortho",
    questionCount: 33,
    tags: ["Fractures", "Dislocations", "Imaging", "Compartment"],
    acem_sections: ["8.1", "8.2"],
    description: "Fracture classification, procedural sedation for reductions, compartment syndrome recognition, and growth plate injury in children.",
  },
  {
    slug: "radiology",
    title: "Radiology",
    shortTitle: "Radiology",
    questionCount: 30,
    tags: ["CXR", "CT", "Ultrasound", "POCUS"],
    acem_sections: ["9.1"],
    description: "Plain film, CT, and POCUS interpretation including FAST exam, lung ultrasound, and DVT assessment.",
  },
  {
    slug: "anaesthesia",
    title: "Anaesthesia & Airway",
    shortTitle: "Airway",
    questionCount: 28,
    tags: ["RSI", "Difficult Airway", "Ketamine", "NMBA"],
    acem_sections: ["10.1", "10.2"],
    description: "RSI drug selection, difficult airway algorithms, awake fibre-optic indications, and post-intubation management.",
  },
  {
    slug: "environmental",
    title: "Environmental Emergencies",
    shortTitle: "Environmental",
    questionCount: 25,
    tags: ["Hypothermia", "Envenomation", "Drowning", "Heat"],
    acem_sections: ["11.1"],
    description: "NZ/AU-specific envenomation (katipo, white-tail, Australian snakes), hypothermia rewarming, and drowning resuscitation.",
  },
  {
    slug: "og",
    title: "Obstetrics & Gynaecology",
    shortTitle: "O&G",
    questionCount: 30,
    tags: ["Ectopic", "PET", "PPH", "PV Bleeding"],
    acem_sections: ["12.1", "12.2"],
    description: "Ectopic pregnancy management, pre-eclampsia treatment thresholds, postpartum haemorrhage MTP activation.",
  },
  {
    slug: "clinical-chem",
    title: "Clinical Chemistry",
    shortTitle: "Clin Chem",
    questionCount: 28,
    tags: ["Electrolytes", "DKA", "HHS", "Acid-Base"],
    acem_sections: ["13.1"],
    description: "DKA vs HHS protocols, hyponatraemia correction rates, hyperkalaemia management, and acid-base problem-solving.",
  },
  {
    slug: "trauma-hfn",
    title: "Trauma — HFN & Burns",
    shortTitle: "Trauma HFN",
    questionCount: 30,
    tags: ["Burns", "Haemorrhage", "Fractures", "Damage Control"],
    acem_sections: ["4.3", "4.4"],
    description: "Burns assessment and fluid resuscitation, haemorrhagic shock management, pelvic fractures, and damage control surgery principles.",
  },
  {
    slug: "trauma-special",
    title: "Trauma — Special Circumstances",
    shortTitle: "Trauma Special",
    questionCount: 25,
    tags: ["Penetrating", "Blast", "Elderly", "Pregnancy"],
    acem_sections: ["4.5"],
    description: "Penetrating trauma, blast injuries, trauma in pregnancy, elderly trauma, and mass casualty triage principles.",
  },
  {
    slug: "vascular",
    title: "Vascular Emergencies",
    shortTitle: "Vascular",
    questionCount: 22,
    tags: ["AAA", "Aortic Dissection", "Limb Ischaemia", "DVT"],
    acem_sections: ["8.3"],
    description: "Ruptured AAA, aortic dissection management, acute limb ischaemia, mesenteric ischaemia, and DVT/PE.",
  },
  {
    slug: "neonates",
    title: "Neonates",
    shortTitle: "Neonates",
    questionCount: 20,
    tags: ["NRP", "Resuscitation", "Jaundice", "Sepsis"],
    acem_sections: ["6.4"],
    description: "Neonatal resuscitation (NRP), neonatal jaundice, early-onset sepsis, congenital heart disease presentations, and neonatal seizures.",
  },
  {
    slug: "ophthalmology",
    title: "Ophthalmology",
    shortTitle: "Ophthalmology",
    questionCount: 20,
    tags: ["Visual Loss", "Globe Injury", "Glaucoma", "CRAO"],
    acem_sections: ["14.1"],
    description: "Acute visual loss, globe rupture, orbital compartment syndrome, acute angle-closure glaucoma, and chemical eye injuries.",
  },
  {
    slug: "ent",
    title: "ENT Emergencies",
    shortTitle: "ENT",
    questionCount: 20,
    tags: ["Epistaxis", "Airway", "Hearing Loss", "Peritonsillar"],
    acem_sections: ["14.2"],
    description: "Epistaxis management, peritonsillar abscess, sudden sensorineural hearing loss, Ludwig's angina, and epiglottitis.",
  },
  {
    slug: "endocrine",
    title: "Endocrine Emergencies",
    shortTitle: "Endocrine",
    questionCount: 22,
    tags: ["Thyroid Storm", "Adrenal Crisis", "Hypoglycaemia", "Phaeochromocytoma"],
    acem_sections: ["13.2"],
    description: "Thyroid storm, myxoedema coma, adrenal crisis, phaeochromocytoma, and hypoglycaemia management in the ED.",
  },
  {
    slug: "derm-id",
    title: "Dermatology & Infectious Disease",
    shortTitle: "Derm/ID",
    questionCount: 22,
    tags: ["Sepsis", "Cellulitis", "SJS", "Meningococcal"],
    acem_sections: ["15.1", "15.2"],
    description: "Meningococcaemia, necrotising fasciitis, Stevens-Johnson syndrome, cellulitis risk stratification, and tropical/travel infections.",
  },
  {
    slug: "gen-surg",
    title: "General Surgery",
    shortTitle: "Gen Surg",
    questionCount: 25,
    tags: ["Appendicitis", "Bowel Obstruction", "Perforated Viscus", "Cholecystitis"],
    acem_sections: ["16.1"],
    description: "Appendicitis, bowel obstruction, perforated viscus, acute cholecystitis, GI haemorrhage, and peri-operative ED care.",
  },
  {
    slug: "admin",
    title: "Administration & Professionalism",
    shortTitle: "Admin",
    questionCount: 26,
    tags: ["Access Block", "NEAT", "Leadership", "Professionalism"],
    acem_sections: ["1.1", "1.2", "1.3"],
    description: "Access block, ED overcrowding, leadership and governance, clinical professionalism, complaints management, and ACEM advocacy.",
  },
];

export function getTopicBySlug(slug: string): VaultTopic | undefined {
  return vaultTopics.find((t) => t.slug === slug);
}
